### ISSUE TITLE
Cannot update site

### ISSUE THREAD

**Issue by dbloom** [ranges-network/ranges-network.github.io#11]
@peterdesmet The issues persist with the commits. I can't update any pages. I don't know enough to know what mistake I've made.  Could you take a look. This is related to #10 I think.

Most recent example: I removed the toc from awards.md and attempted to make some text edits and a hyperlink.

Result:

https://github.com/ranges-network/ranges-network.github.io/actions/runs/6725650036

[build](https://github.com/ranges-network/ranges-network.github.io/actions/runs/6725650036/job/18280473031#step:4:115)
 Logging at level: debug Configuration file: /github/workspace/./_config.yml Theme: minima Theme source: /usr/local/bundle/gems/minima-2.5.1 GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: minima Theme source: /usr/local/bundle/gems/minima-2.5.1 Requiring: jekyll-feed Requiring: jekyll-seo-tag Requiring: jekyll-feed Requiring: jekyll-sitemap Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings Requiring: jekyll-remote-theme GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... Theme: peterdesmet/petridish@3.0 Theme source: /tmp/jekyll-remote-theme-20231101-9-160jqw6 Remote Theme: Using theme peterdesmet/petridish Remote Theme: Downloading https://codeload.github.com/peterdesmet/petridish/zip/3.0 to /tmp/jekyll-remote-theme-20231101-9-139bcx5.zip Remote Theme: Unzipping /tmp/jekyll-remote-theme-20231101-9-139bcx5.zip to /tmp/jekyll-remote-theme-20231101-9-160jqw6 EntryFilter: excluded /Gemfile EntryFilter: excluded /README.md Generating: JekyllOptionalFrontMatter::Generator finished in 0.000425506 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.003392447 seconds. Jekyll Feed: Generating feed for posts Generating: JekyllFeed::Generator finished in 0.000904512 seconds. Generating: Jekyll::JekyllSitemap finished in 0.00074171 seconds. Generating: Jekyll::Paginate::Pagination finished in 6.1e-06 seconds. Generating: JekyllRelativeLinks::Generator finished in 0.002067429 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.000229704 seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 4.72e-05 seconds. Rendering: pages/about.md Pre-Render Hooks: pages/about.md Rendering Markup: pages/about.md Requiring: kramdown-parser-gfm Rendering Layout: pages/about.md Layout source: theme GitHub Metadata: Generating for ranges-network/ranges-network.github.io GitHub Metadata: Calling @client.pages("ranges-network/ranges-network.github.io", {}) Rendering: pages/awards.md Pre-Render Hooks: pages/awards.md Rendering Markup: pages/awards.md Rendering Layout: pages/awards.md Layout source: theme Rendering: pages/home.md Pre-Render Hooks: pages/home.md Rendering Markup: pages/home.md Rendering Layout: pages/home.md Layout source: theme Rendering: pages/news.md Pre-Render Hooks: pages/news.md Rendering Markup: pages/news.md Rendering Layout: pages/news.md Layout source: theme Rendering: pages/participants.md Pre-Render Hooks: pages/participants.md Rendering Markup: pages/participants.md Rendering Layout: pages/participants.md Layout source: theme Rendering: pages/privacy.md Pre-Render Hooks: pages/privacy.md Rendering Markup: pages/privacy.md Rendering Layout: pages/privacy.md Layout source: theme Rendering: pages/team.md Pre-Render Hooks: pages/team.md Rendering Markup: pages/team.md Rendering Layout: pages/team.md Layout source: theme Rendering: assets/theme/css/main.scss Pre-Render Hooks: assets/theme/css/main.scss Rendering Liquid: assets/theme/css/main.scss Rendering Markup: assets/theme/css/main.scss github-pages 228 | Error: String can't be coerced into Integer Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20231101-9-160jqw6

**Comment by dbloom** [comment]
Just thinking out loud - I did change the name of page `archive.md` to `news.md`. I don't think that had anything to do with this, but I don't know. I also created folder `_posts`. Create/renamed a few readme.md files, too. I can't think of anything else. The issue started when I attempted to add toc to `privacy.md`. Then the world went dark and I started seeing dragons.

**Comment by peterdesmet** [comment]
At the very end of the log it says:

> String can't be coerced into Integer

This issue has popped up a couple of times across Jekyll websites. It has nothing to do with something you did: I believe it is a race condition in the Jekyll processing (some processing finishing before it gets the result from another). That makes it annoying to debug, because sometimes it will pop up and then the next run (on the next commit) works fine (as you can notice in your list of [commits](https://github.com/ranges-network/ranges-network.github.io/commits/main)).

I don't have a good way to avoid it. You can fix it _without doing another commit_ by going to the failed action and clicking `Re-run failed action`:

<img width="976" alt="Screenshot 2023-11-02 at 12 19 55" src="https://github.com/ranges-network/ranges-network.github.io/assets/600993/d64141d4-8cac-4158-8e70-21ae41863594">

**Comment by dbloom** [comment]
This is very helpful to know. I have re-run and it worked just fine. It also taught me something about the Actions tab, which I have been wondering about. Thank you.
