### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by dbloom** [ranges-network/ranges-network.github.io#3]
@peterdesmet I've been attempting to see if I can get the links in the Footer to open in a new tab. It just may not be possible in markdown, but it seems worth a shot.

I've tried unsuccessfully:

href: "https://futres.org/" target="_blank"
href: http://vertnet.org/ target="_blank"
href: https://geome-db.org/?to=/_blank
href: <a href="https://futres.org/" target="_blank">
href: http://vertnet.org/ {:target="_blank"}
href: (http://vertnet.org/){:target="_blank"}

Looked at resources such as https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link and https://wordpress.com/forums/topic/how-to-open-custom-html-link-to-open-in-new-tab/#:~:text=You%20can%20make%20a%20HTML,this%20after%20the%20link%20address. So it may be possible, or only possible for links embedded within text/paragraphs, but I have not found a method for doing so for links using the footer format with text: and href:.

If you know of a way, I would am eager to know what it might be.

**Comment by peterdesmet** [comment]
@dbloom the solutions above might work in the markdown of the page, but the footer links are a Petridish thing. And apparently I have implemented support for new tabs 🙌. Just add `new_window: true` to the link, cf:

https://github.com/peterdesmet/petridish/blob/efb9a64438086376f9f36dd8df6cd93caefa9aa9/_data/navigation.yml#L24

**Comment by dbloom** [comment]
Awesome! I will try it pronto. Many thanks.

**Comment by dbloom** [comment]
Works!  Yea!

**Comment by dbloom** [comment]
Closed
