### ISSUE TITLE
GoogleScholar goes to login page

### ISSUE THREAD

**Issue by dbloom** [ranges-network/ranges-network.github.io#4]
@peterdesmet 

If find that when using the "googlescholar: xxxxx" option in the team.yml does not open the expected page. instead of opening the team member's gScholar page it takes me to a generic Google login page, or, if I am logged into Google in the browser I am taken to a my google profile page, asking me if I want to track citations associated with my account.

I have tested this in Safari, FF, and Chrome with the same results in all three.  This is the case if I use the gScholar login (e.g., dbloom) or if I use the full link (e.g., https://scholar.google.com/citations?user=W3QL51QAAAAJ&hl=en).

**Comment by peterdesmet** [comment]
You should only add their Google Scholar User ID in the yaml:

```
googlescholar: W3QL51QAAAAJ
```

Petridish will prepend this with `https://scholar.google.com/citations?user=`

**Comment by dbloom** [comment]
Yes, and I'm keeping only those for which I have the user ID. Clicking on the icon still results in the same things - either my profile page or a google log in page.

**Comment by peterdesmet** [comment]
Have you tried with the ID (DPABkrgAAAAJ, not bryansmclean)? I only see names in https://github.com/ranges-network/ranges-network.github.io/blob/main/_data/team.yml

**Comment by dbloom** [comment]
Dagummit! I had those IDs in there from the start, but removed them when I was trying to debug something else, just failed to connect A to B and put them back in. 

Working now, although it's good for me to know what happens when you use the other user ID.

Many beers or 20-sided dice you are earning my master.
